### ISSUE TITLE
Disable auto-merging of dependency upgrades in mergify.yml

### ISSUE THREAD

**Issue by tan-zx** [opengovsg/ts-template#1369]
In [mergify.yml](https://github.com/opengovsg/ts-template/blob/develop/.github/mergify.yml), currently non-major dependabot upgrades  areautomatically merged into `develop`

I discussed with @timotheeg and @lamkeewei, it seems like this is a bad idea:
- It's probably not safe to assume that even semver patches won't accidentally introduce breaking changes (much less maliciously: see the recent [`node-ipc` example here](https://arstechnica.com/information-technology/2022/03/sabotage-code-added-to-popular-npm-package-wiped-files-in-russia-and-belarus/))
- If we are interested in getting timely security updates, I think there are already other less intrusive measures to do so by GitHub and Snyk

It might be OK to do automatic merging if the repo is v well-tested, so that we can be sure that everything works as intended. But I think that's not a standard that we can assume all repos meet this standard.

In fact, for mission-critical products, it might be even better to err on the side of caution and pin dependencies to explicit versions and do controlled, tested upgrades. 

As such, insofar as ts-template is supposed to embody a set of safe defaults, I don't think the current auto-merging of dependencies upgrade is such a default. 

(As a side note, can I be given access rights to this? Tried to create a PR but was blocked.)

**Comment by tan-zx** [comment]
Example of dependency-pinning: https://github.com/opengovsg/postmangovsg/pull/1578

**Comment by LoneRifle** [comment]
Given that ts-template is meant to be a starting base for new products built by engineering, we want to keep deps in this particular repository as recent as possible, to ensure that they start with the most recent packages.

This should be sustained even as engineers continue to build out their product; any stability risk from dep changes can be mitigated by the fact that the products would not be heavily used in its early days.

Engineers are free to discard the rolling dep updates at any point in their dev process once this template is used to start their codebase.
