### ISSUE TITLE
Migrate default versions to current LTS: Node 14, Linux 20.04

### ISSUE THREAD

**Issue by madanalogy** [opengovsg/ts-template#654]
**Is your feature request related to a problem? Please describe.**

New projects being spun up should be up to date on the latest LTS versions. Relying on older LTS versions will lead to a shorter development window before needing to update a deprecated version. 

**Describe the solution you'd like**

Upgrade base Node version to current LTS (v14) in:
- Docker environment: `node:14-alpine`
- GitHub Actions CI workflow: `node-version: '14.x'`

Upgrade CI to use current Linux LTS (v20.04): `runs-on: ubuntu-20.04`

**Additional context**

Elastic beanstalk and AWS lambda both support Node 14
- https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html#platforms-supported.nodejs
- https://aws.amazon.com/blogs/compute/node-js-14-x-runtime-now-available-in-aws-lambda/

**Comment by LoneRifle** [comment]
Fixed in 49287d2
