### ISSUE TITLE
Add documentation on how to set up and migrate DB

### ISSUE THREAD

**Issue by prestonlimlianjie** [opengovsg/ts-template#789]
Add guides on how to set up a database and how to run migrations

**Comment by lamkeewei** [comment]
Just a random thought, do you think it will be worthwhile to look into whether we can programmatically apply database migrations as part of our deployment pipeline? 

Jean added [some code](https://github.com/opengovsg/ts-job-template/blob/develop/backend/src/util/create-pg-client.ts) in the `ts-job-template` repo that establishes a tunnel to a database instance sitting behind a private subnet. It should be possible to modified it for this purpose. 

This could potentially help avoid human error and reduce the need for engineers to directly connect to and modify production databases. It can also make deployment safer and more stress-free.

Though with that said, I can definitely see some rather significant security tradeoffs. This is especially so given that we don't own the machines that our CI/CD pipeline runs on. For example, we will have to whitelist the [IP addresses where GitHub runners](https://docs.github.com/en/enterprise-server@2.22/actions/using-github-hosted-runners/about-github-hosted-runners#ip-addresses) are running on. Happy to hear some thoughts on this!

**Comment by prestonlimlianjie** [comment]
Automating migrations makes sense - the lambda suggestion is a good idea

**Comment by prestonlimlianjie** [comment]
After the sync-up discussion:
- we decided should treat the `ts-template` repo as infrastructure agnostic, and we should have an in-memory datastore
- as such, we will run migrations locally for now
