### ISSUE TITLE
Setup backend logging

### ISSUE THREAD

**Issue by lamkeewei** [opengovsg/ts-template#790]
Setup backend logging with `winston` (or another library) with example transports for different environment (local, staging, production).

**Comment by LoneRifle** [comment]
consider porting something similar to datagovsg/helpgovsg#452

**Comment by karrui** [comment]
I think @mantariksh is interested in this. Should wait till #798 is complete though.

**Comment by mantariksh** [comment]
"interested" is a strong word but yes I can work on this

(just kidding I'm happy to do it)
